DELETE Clients
DELETE Animals
DELETE Species
DELETE Breeds
DELETE Colours

DBCC CHECKIDENT ('Clients', RESEED, 0)
DBCC CHECKIDENT ('Animals', RESEED, 0)
DBCC CHECKIDENT ('Species', RESEED, 0)
DBCC CHECKIDENT ('Breeds', RESEED, 0)
DBCC CHECKIDENT ('Colours', RESEED, 0)